author: mobin habibpour 98201727

mobin.habibpour@gmail.com

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# zero-padding
def zero_pad(input, p):
  result = np.zeros((input.shape[0] + 2*p, input.shape[1] + 2*p))
  result[p:input.shape[0]+p,p:input.shape[1]+p] = input
  return result

In [ ]:
def conv_forward(input, kernel, stride, padding):
    
    f = kernel.shape[0]
    if input.shape == 3:
      w, h, c = input.shape
      conv = np.zeros((int((w-f+2*padding)/stride)+1,int((w-f+2*padding)/stride)+1,c))
    else: 
      w, h = input.shape
      c = 1
      conv = np.zeros((int((w-f+2*padding)/stride)+1,int((w-f+2*padding)/stride)+1))

    input = zero_pad(input, p=padding)

    for jj in range(c):
      for x in range(input.shape[0]-f+1):
        for y in range(input.shape[1]-f+1):
          conv[x,y] = np.sum(input[x:x+f,y:y+f]*kernel)
          if c > 1:
            conv[x,y,jj] = np.sum(input[x:x+f,y:y+f,:]*kernel[jj])
    return conv
    

In [ ]:
def maxpool_forward(input, pool_size, stride):

    if input.shape == 3:
        w, _, c = input.shape
        pool = np.zeros((int((w-pool_size)/stride)+1, int((w-pool_size)/stride)+1), c)
    else: 
      w, _ = input.shape
      c = 1
      pool = np.zeros((int((w-pool_size)/stride)+1, int((w-pool_size)/stride)+1))
    
    for jj in range(0,c):
      i=0
      while(i<w):
        j=0
        while(j<w):
          pool[int(i/2),int(j/2)] = np.max(input[i:i+pool_size,j:j+pool_size])
          j+=stride
        i+=stride
    return pool

In [ ]:
input = np.array([[3,3,4,4,7,0],
                  [9,7,6,5,8,2],
                  [6,5,5,6,9,2],
                  [7,1,3,2,7,8],
                  [0,3,7,1,8,3],
                  [4,0,4,3,2,2]])

kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]]) 

In [ ]:
conv = conv_forward(input,kernel,stride=1, padding=1)
print(conv)

[[-10.   2.   1.  -5.   7.  15.]
 [-15.   3.   0.  -9.  11.  24.]
 [-13.   8.   0. -10.   1.  24.]
 [ -9.  -2.   0.  -9.  -4.  24.]
 [ -4.  -3.  -2.  -3.  -7.  17.]
 [ -3.  -7.  -1.   1.  -1.  10.]]


In [ ]:
pool = maxpool_forward(conv, pool_size=2, stride=2)
print(pool)

[[ 3.  1. 24.]
 [ 8.  0. 24.]
 [-3.  1. 17.]]
